name: Pipeline Practica Experimental

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting (syntax check)
        run: |
          python -m py_compile $(find my-app -name "*.py")

      - name: Run tests
        run: |
          if [ -d "tests" ]; then
            pip install pytest
            pytest tests --junitxml=reports/report.xml || true
          else
            echo "No tests directory found"
          fi

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports/report.xml
